### ISSUE TITLE
Documentation/comments are a bit unclear, clarify?

### ISSUE THREAD

**Issue by x5nder** [nylonee/watchlistarr#100]
I'm installing Watchlistarr for the first time and got confused editing the yaml configuration file.

`skipfriendsync: false # Don't sync friends watchlists, only your own`

The comment is the exact opposite of what the default action seems to be doing. I assume 'false' means it _doesn't_ skip the friend sync, right? So either the comment is wrong, or the variable should have been called 'friendsync'.

More important is the Delete Sync configuration; I don't want to run _any_ risk in any app removing movies and shows from Sonarr/Radarr or my hard drive. However, generally, applications default to 'true' for their behavior. So does that mean, if I leave the Delete Sync configuration alone (as in, I don't uncomment it), delete is 'true' for movie, endedShow and continuingShow and Watchlistarr will actually remove anything not on my watchlist?

**Comment by nylonee** [comment]
You're right this is probably a little confusing!

The reasoning for some of these is to maintain backwards compatibility, as many of these config variables have been added after an initial release of Watchlistarr. Going by the principle of least surprise, I don't want to change how anybody's Watchlistarr works every time they update.

The default for ALL delete functionality by default is set to `false`. It will NOT delete things unless you go in and change the config.

As for the `skipfriendsync`, if it's set to `false` (which is the default for legacy purposes, though I'd have preferred it to be `true` by default), it will NOT skip syncing your friend's watchlists. Setting it to `true` will only sync your own watchlist, ignoring your friends.

Again, you've raised a very valid point though about confusing configuration. I'll go into the config.yaml and add some more details into each config to indicate what the default is and how it works.

**Comment by x5nder** [comment]
Thanks, and that's great information-- this makes me feel a lot more confident starting up your tool :)

**Comment by nylonee** [comment]
No worries! Glad you're able to get it working now and it's clearer. I've raised a PR to add some more clarify to the config template, let me know if you think there's anything else I'm missing :)
