### ISSUE TITLE
Latest release (0.2.0) doesn't contain jar file in assets

### ISSUE THREAD

**Issue by bony2023** [nylonee/watchlistarr#101]
As mentioned in the title, the latest release doesn't contain the watchlistarr.jar file.

**Comment by nylonee** [comment]
Ack, you're right, looks like the [build failed](https://github.com/nylonee/watchlistarr/actions/runs/7947490427/job/21696369252)

I'll take a look at this sometime today, thanks for raising this!

**Comment by nylonee** [comment]
All right I've fixed it and pushed the fix to a new release, should be okay on `v0.2.1`
Let me know if you still have any issues :)
