### ISSUE TITLE
Unable to fetch sonarr baseUrl, using default http://localhost:8989

### ISSUE THREAD

**Issue by profusse** [nylonee/watchlistarr#107]
Good morning
The container does not start because it cannot connect to sonarr and radarr but it uses the default baseurl (localhost). The container is therefore unable to join another container. How to specify the IP of sonarr and radarr.
Sincerely

`23:19:06.776 [main] WARN  configuration.ConfigurationUtils$ - Unable to fetch sonarr baseUrl, using default http://localhost:8989
23:19:07.269 [io-compute-2] ERROR configuration.ConfigurationUtils$ - Unable to connect to Sonarr at http://localhost:8989, with error java.net.ConnectException: Connection refused
java.lang.IllegalArgumentException: Unable to connect to Sonarr at http://localhost:8989, with error java.net.ConnectException: Connection refused
	at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:263)
	at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$4(ConfigurationUtils.scala:93)
	at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
	at flatMap @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
	at main$ @ Server$.main(Server.scala:11)
	at getAndSet @ org.typelevel.keypool.KeyPool$.destroy(KeyPool.scala:120)
	at clear @ org.http4s.client.middleware.FollowRedirect$.redirectLoop$1(FollowRedirect.scala:105)
	at clear @ org.http4s.client.middleware.FollowRedirect$.redirectLoop$1(FollowRedirect.scala:105)`

**Comment by noisymime** [comment]
This appears to be a problem for anyone who is using the default docker setups for their sonarr/radarr installs. I'd suggest that watchlistarr should also attempt to connect via the external interface of the host as well as `localhost`. 

Additionally, neither of the options that seem to exist for specifying the sonarr/radarr hosts manually seems to work. 
I've tried setting the `SONARR_BASE_URL` env variable and uncommenting the relevant lines in config.yml and setting the address there, but both of these appear to get ignored when creating the container and it falls back to using `localhost:8989`, which fails.

**Comment by noisymime** [comment]
Apologies, it looks like the environment variables do work, they just need to specified in full strings. Eg:

```
 -e SONARR_BASE_URL="http://192.168.0.1:8989" \
 -e RADARR_BASE_URL="http://192.168.0.1:7878" \
```

Rather than simply:

```
 -e SONARR_BASE_URL=192.168.0.1:8989 \
 -e RADARR_BASE_URL=192.168.0.1:7878 \
```

I'd still suggest that the default behaviour should be changed to look for the external interface address so that the default sonarr/radarr containers will work.

**Comment by nylonee** [comment]
Thanks for this, it does indeed look like I need to clean up the default behaviour a bit to look in a few more places for a sonarr/radarr instance. If running within docker, the localhost also needs to be changed to `host.docker.internal`.

**Comment by nylonee** [comment]
> I've tried setting the SONARR_BASE_URL env variable and uncommenting the relevant lines in config.yml and setting the address there, but both of these appear to get ignored when creating the container and it falls back to using localhost:8989, which fails.

This is also a bit worrying, as it indicates to me that the config.yml file isn't being read properly into the app. Feel free to raise a new issue if this is indeed the case and I'll look into it

**Comment by raogopoko** [comment]
@nylonee , thank you for your time. When do you think that you will be able to fixe the 
Unable to fetch sonarr baseUrl, using default http://localhost:8989 problem?
No config.yaml created after installation in the specify folder.

Again thank you

**Comment by nylonee** [comment]
I've fixed this now and there should be updated documentation here to help you navigate the changes:
https://github.com/nylonee/watchlistarr/blob/main/CONFIGURATION.md
