### ISSUE TITLE
not working for Plex Home / Managed Users only for main account.

### ISSUE THREAD

**Issue by Rikiar73574** [nylonee/watchlistarr#111]
i don't know if this is the most used scenario, but items from other managed users do not appear to translate over to radarr/sonarr.
I personally would use this a lot more so people using my plex don't have to use a separate plex account in my home.

**Comment by nylonee** [comment]
This is on the roadmap, I think it was a recent addition that managed users are allowed to watchlist items. Thanks for raising this issue!

**Comment by nylonee** [comment]
Okay I've had a click around on managed users, this is a bit weird, it looks like Managed Users don't have access to the Discover tab, however they can still watchlist things that are already in your library?

If so, I imagine the use case of watchlistarr is fairly limited, as managed users won't be able to request new content, only 'preserve' content if you're using the delete-sync aspect of watchlistarr

**Comment by nylonee** [comment]
Closing this for now until Managed Users have better control over the watchlist
