### ISSUE TITLE
FULL DELETE SYNC

### ISSUE THREAD

**Issue by jaeuwi74** [nylonee/watchlistarr#151]
hello,

if I activate these options, 
will the content of films and series be permanently deleted from the hdd or just deleted from radarr and sonarr and the films and series kept on the hdd?

#################################################################
#################################################################
movie: true
endedShow: true 
continuingShow: false 
interval.days: 7

**Comment by HYWUD** [comment]
I can answer that because I just experienced it. The movie:true started deleting my movies. Thankfully I was checking and it only deleted about 30. Could have been way worse.

**Comment by nylonee** [comment]
Hello! Sorry for the late response, yes that's right, the delete sync will also delete the files. Are you looking for an option where it only deletes the Movie/TV show off Sonarr/Radarr and not touch the file storage?

**Comment by nylonee** [comment]
I've added a configuration parameter to allow you to choose whether you want the content to be deleted off your system, or only as an entry in Sonarr/Radarr. Hope this helps!
https://github.com/nylonee/watchlistarr/pull/154
