### ISSUE TITLE
Set User Agent

### ISSUE THREAD

**Issue by markus101** [nylonee/watchlistarr#156]
Related to https://github.com/nylonee/watchlistarr/issues/128 I see that issue the user agent is/was `http4s-ember/0.23.23`.

For Sonarr we send one of two different user agents. `Sonarr/4.0.5.1719 (Windows 10.0.22631.0` or `Sonarr/4.0`, which also any other apps/services we're connecting to more easily report issues and in extreme cases block specific versions that are known to have issues so that users can update.

For Sonarr this could allow us to prevent repetitive requests from logging the same error.

**Comment by nylonee** [comment]
Oohh interesting, so to understand what you're saying, you'd prefer for Watchlistarr to set the user agent to something along the lines of `Watchlistarr/*` when it's connecting to Sonarr?

Happy to pop this fix in, would this mean that Sonarr would be able to reduce the warnings for calling a deprecated API (as is mentioned in the earlier issue)

**Comment by markus101** [comment]
I'm not sure, but we may be able to do something about them.
