### ISSUE TITLE
Sonarr: API call made to deprecated endpoint from watchlistarr/1.0 

### ISSUE THREAD

**Issue by wokkieman** [nylonee/watchlistarr#164]
Hi, 

Error in Sonnarr logs is: [Warn] ImportListExclusionController: API call made to deprecated endpoint from watchlistarr/1.0 
It repeats a lot, so I guess it's trying to update Sonarr :)

I use latest docker of Sonarr (v4)

No issues reported in Watchlistarr logs

**Comment by nylonee** [comment]
Hi thanks for raising this, this is the same issue as https://github.com/nylonee/watchlistarr/issues/128, so I'll close this issue so we can track progress in one place :)

**Comment by wokkieman** [comment]
Ah sorry, thanks for pointing to that one!
