### ISSUE TITLE
Delete movies/tv shows that have been removed from watchlist

### ISSUE THREAD

**Issue by nylonee** [nylonee/watchlistarr#17]
A full sync with the watchlist would be nice, including deleting items once they're removed from all watchlists. At the moment this isn't really possible with RSS feeds because it shows a maximum of 50 movies/shows, so we need to load in the plex token for this functionality.

Contributions welcome

**Comment by nylonee** [comment]
Looks like it's possible to have a long-lived plex token as long as you regularly validate it, which updates the expiry https://github.com/Sonarr/Sonarr/issues/5154

**Comment by nylonee** [comment]
Okay the complexity here is that we don't have an easy way of fetching the watchlist for friends using the plex token. We have a GraphQL call which I kinda reverse-engineered because introspecting has been disabled, but it's only giving me the name of the movie/show on somebody's watchlist, whereas I'd like to match on an ID of some kind. So this is still a WIP

**Comment by abaudhuin** [comment]
This should be optin only. 
I probably don't want my friends to be able to remove shows from my server.

**Comment by nylonee** [comment]
Yeah I think the plan is to be opt-in when it's ready.

I've completed the watchlist sync part of things, just having a think now about how to do the deleting.
