### ISSUE TITLE
How adding shows work, and how delete sync works

### ISSUE THREAD

**Issue by tiagodj** [nylonee/watchlistarr#175]
Hi,

I tried finding answers to these questions in the docs and other issues, but couldn't.

* When adding a Series, does it add/monitor all episodes, only the first season, or what? I usually prefer to monitor only the Pilot because sometimes I am not sure I will like it.
* When enabling delete sync, does it delete the shows that are NOT in the watchlist in the first place? or does it ignores them and only deletes the ones that are removed from watchlist?

Thanks

**Comment by nylonee** [comment]
Hello! These are good questions and I'll make sure it's included in the docs:

1. This is configurable, I'm on my phone and can't remember off the top of my head, but if you look under the config -> Sonarr settings, there's a setting you can choose to either send all episodes for download, or only certain episodes.

2. The app can't distinguish between shows that weren't on the watchlist to begin with, and shows that have been removed off the watchlist, so it'll aggressively delete everything that's not on the watchlist

**Comment by tiagodj** [comment]
1. I feel stupid. there's an option in your config file `seasonMonitoring: pilot` which I configured. So no issues there.
2. For this, what I expected was, when starting the server, don't aggressively delete what's not on the watchlist. Only triggers the delete when the user actively removes something from the watchlist. This way, there is no risk of starting up the service and deleting a lot of stuff by accident. the downside is to have to add everything to the watchlist to be able to delete it. but that is safer, imho.

either way, thanks for the answers. you can close this.
