### ISSUE TITLE
[Feature Request] Add query strings to RSS feed to bypass cache and improve performance

### ISSUE THREAD

**Issue by jmsprsns** [nylonee/watchlistarr#180]
Plex caches their RSS feeds with a relatively short window, so they can be stale for a few minutes; sometimes up to 20 minutes, as some users report. 

This is easily bypassed by adding a query string like ?1 or ?2 or ?3 after the URL. 

It would be great to incorporate this into the app somehow to reduce caching-related delays.

**Comment by tiredjohn** [comment]
Discussed here: https://github.com/nylonee/watchlistarr/issues/182
PR with this feature added: https://github.com/nylonee/watchlistarr/pull/183

**Comment by jmsprsns** [comment]
Nice! Glad this solved the issue. Cheers
