### ISSUE TITLE
Improvement Idea

### ISSUE THREAD

**Issue by richowen** [nylonee/watchlistarr#24]
**GitHub Issue: Configure Season Monitoring in Sonarr using Environment Variable**

**Issue Description:**
Currently, shows added to Sonarr are automatically monitoring all seasons by default. It would be beneficial to have the option to configure this behavior through an environment variable.

**Proposed Solution:**
Add an environment variable, let's call it `SONARR_SEASON_MONITORING`, with the following options:

```scala
["all", "future", "missing", "existing", "pilot", "firstSeason", "latestSeason", "none"]
```

**Current Implementation:**
The current implementation hard-codes the monitoring of all seasons in the `SonarrAddOptions` case class:

```scala
private case class SonarrAddOptions(
  monitor: String = "all",
  searchForCutoffUnmetEpisodes: Boolean = true,
  searchForMissingEpisodes: Boolean = true
)
```

**Comment by nylonee** [comment]
This is a great idea, did you come up with that list of monitor parameters or is that from the official Sonarr API docs? I can't find it

**Comment by nylonee** [comment]
Ah yes just found it [here](https://github.com/Sonarr/Sonarr/blob/e68b13940d4dd4c5fd008884d909e614521c8cee/frontend/src/Utilities/Series/monitorOptions.js#L47)
Fantastic, I will add that now

**Comment by richowen** [comment]
https://github.com/Sonarr/Sonarr/blob/e68b13940d4dd4c5fd008884d909e614521c8cee/src/Sonarr.Api.V3/openapi.json#L9604C7-L9604C7 or here if that helps

**Comment by richowen** [comment]
i got it to monitor the latest season on my fork, but it only monitors the season not the episodes in the season, weird

**Comment by nylonee** [comment]
I just tried with latest season and it monitored all the episodes within the season too, perhaps it's different for different shows

**Comment by nylonee** [comment]
I've raised a PR with the changes, you could try the latest alpha tag to see if you can get it to work, I'll wait for your confirmation before merging

**Comment by richowen** [comment]
hmm ok im using latestSeason and for shows that are "continuing" on sonarr it works great, but shows that are "ended" on sonarr dont monitor the individual eps, so it looks like a sonarr thing

**Comment by richowen** [comment]
![image](https://github.com/nylonee/watchlistarr/assets/11855858/eb6cf2b5-609c-4064-a8de-ebc6e7d3f550)

![image](https://github.com/nylonee/watchlistarr/assets/11855858/2c691d87-8400-465b-8ae0-f3ffbf4075de)

**Comment by nylonee** [comment]
Ah yes this looks like a bug on Sonarr's side. If the season ended more than 90 days ago, it will unmonitor all episodes. I've raised a [bug ticket](https://github.com/Sonarr/Sonarr/issues/6175). In the meantime, I think this PR is good to go in as the rest of the monitoring options will still work.
