### ISSUE TITLE
Add ability to add tags to requests

### ISSUE THREAD

**Issue by Dynamonoodle** [nylonee/watchlistarr#41]
As a user, I would like the ability to add tags to series and movies that are coming in to Sonarr/Radarr as requests from Watchlistarr.

Very similar to the functionality found in Overseerr: 

![IMG_5246](https://github.com/nylonee/watchlistarr/assets/151488614/db6d058a-ecbb-4ff8-8f45-b65a20a7b3a3)

**Comment by nylonee** [comment]
It looks like the arr apps do this in a multi-step process:

1. Have a list of pre-existing tags via a GET to `/api/v3/tag`
2. If the tag doesn't exist, create a new tag with an unassigned ID via a POST to `/api/v3/tag`
3. Fetch a list of tags including the newly created tag and its id
4. Inject the ID as part of the request (by adding an array `tags` with the list of IDs to inject)

We could probably implement this by doing:

1. Provide the list of tags (strings) desired in environment variables, comma separated
2. During initial configuration of Watchlistarr, check if the tags exist. If they do not, create them. Store the array of IDs in Configuration
3. inject the array of Ids every time a request needs to be synced to the -arrs

One caveat with this implementation is that changing the tags in the -arrs requires a restart of Watchlistarr. Perhaps there's another way to regularly check and keep the list of tags available updated.

**Comment by stamatis921** [comment]
Hi, just checking to see if this is implemented? And if so how to add tags?

**Comment by nylonee** [comment]
Hi, not yet, but I'll be implementing it soon

**Comment by nylonee** [comment]
Hi @stamatis921 this should be in the beta release of Watchlistarr now, you can set the tags using `SONARR_TAGS` and `RADARR_TAGS` for docker, or `sonarr.tags` and `radarr.tags` for Java.

The tags you specify are comma separated (spaces don't matter) and case insensitive, so for example:
```
SONARR_TAGS=request,PLEX, Watchlistarr
// This generates the tags: [request], [plex] and [watchlistarr]
```

**Comment by stamatis921** [comment]
@nylonee This is fantastic! Really helps with my Radarr flow. Appreciate you!
