### ISSUE TITLE
Running on Windows?

### ISSUE THREAD

**Issue by Jusremo** [nylonee/watchlistarr#53]
Extremely interested in the 'Plex Watchlist GraphQL Call' for monitoring watchlists of friends.

Trying to run the .jar on Windows, can't seem to run it with the arguments.

No matter what I do I get
`11:34:12.701 [main] WARN  configuration.ConfigurationUtils$ - Unable to fetch sonarr baseUrl, using default http://localhost:8989
11:34:12.784 [main] ERROR configuration.ConfigurationUtils$ - Unable to find sonarr API key
Exception in thread "main" java.lang.IllegalArgumentException: Unable to find sonarr API key
        at configuration.ConfigurationUtils$.throwError(ConfigurationUtils.scala:164)
        at configuration.ConfigurationUtils$.$anonfun$getSonarrConfig$3(ConfigurationUtils.scala:51)
        at scala.Option.getOrElse(Option.scala:201)
        at configuration.ConfigurationUtils$.getSonarrConfig(ConfigurationUtils.scala:51)
        at configuration.ConfigurationUtils$.create(ConfigurationUtils.scala:18)
        at Server$.run(Server.scala:25)
        at cats.effect.IOApp.main(IOApp.scala:396)
        at cats.effect.IOApp.main$(IOApp.scala:333)
        at Server$.main(Server.scala:11)
        at Server.main(Server.scala)`

**Comment by nylonee** [comment]
Hi! Could you share the command that you used to run the jar?

The error you're seeing is because the app is trying to find the sonarr API key, have you defined it by adding:
```
-Dsonarr.apikey=YOUR_API_KEY
```

To your jar command?

**Comment by nylonee** [comment]
Also

> Extremely interested in the 'Plex Watchlist GraphQL Call' for monitoring watchlists of friends.

I think the latest jar that's released doesn't have this functionality, I've kicked off a new release, make sure you're using v0.0.11 as this will have that functionality (and set your plex Token)

**Comment by Jusremo** [comment]
so this should work?
`java -jar watchlistarr.jar -Dsonarr.apikey=XXXX`

also tried a few other variations, but everything returns the same initial error.
Appreciate the help and quick response.

**Comment by nylonee** [comment]
You will need to add the two other required fields, see the [Java section of the README](https://github.com/nylonee/watchlistarr?tab=readme-ov-file#java)

So at a very minimum:
```
java -jar watchlistarr.jar -Dsonarr.apikey=XXXX -Dradarr.apikey=XXXX -Dplex.watchlist1=YOUR_PLEX_WATCHLIST_URL
```

Then you can also add `-Dplex.token=XXXX` when you've confirmed it's starting up fine

**Comment by Jusremo** [comment]
Same error, running with java 21.0.1.0 on Windows 10.

**Comment by nylonee** [comment]
What about passing them before the -jar rather than after?

```
java -Dsonarr.apikey=XXXX -Dradarr.apikey=XXXX -Dplex.watchlist1=YOUR_PLEX_WATCHLIST_URL -jar watchlistarr.jar
```

**Comment by Jusremo** [comment]
I had tried running it in powershell with the arguments before -jar originally and it hadn't worked, but now running it in CMD it does seem to be accepting arguments! Just going to finish adding all the arguments and I'll let you know, thanks a lot for the help!

**Comment by Jusremo** [comment]
Working with 
`java -Dsonarr.apikey=X -Dradarr.apikey=X -Dplex.watchlist1=X -Dsonarr.baseUrl=X -Dradarr.baseUrl=X -Dsonarr.qualityProfile=1080p -Dradarr.qualityProfile=X -Dsonarr.rootFolder="Path" -Dradarr.rootFolder="Path" -Dplex.token=X -Dsonarr.seasonMonitoring=latestSeason -Dinterval.seconds=30 -jar watchlistarr.jar`

Thanks again for your help.

**Comment by nylonee** [comment]
Nice, good to know, I'll update the readme with the correct ordering of parameters. Thanks for confirming!
