### ISSUE TITLE
Watchlists of Friends Not Syncing

### ISSUE THREAD

**Issue by Jusremo** [nylonee/watchlistarr#54]
Running using Java with this command
`java -Dsonarr.apikey=X -Dradarr.apikey=X -Dplex.watchlist1=X -Dsonarr.baseUrl=X -Dradarr.baseUrl=X -Dsonarr.qualityProfile=1080p -Dradarr.qualityProfile=1080p -Dsonarr.rootFolder="Path" -Dradarr.rootFolder="Path" -Dplex.token=X -Dsonarr.seasonMonitoring=latestSeason -Dinterval.seconds=30 -jar watchlistarr.jar`

and I get this result
`14:44:11.038 [io-compute-7] INFO  configuration.ConfigurationUtils$ - Successfully connected to Sonarr
14:44:11.114 [io-compute-5] INFO  configuration.ConfigurationUtils$ - Successfully connected to Radarr
14:44:11.889 [io-compute-7] INFO  PingTokenSync$ - Refreshed the access token expiry
14:44:11.901 [io-compute-1] INFO  PlexTokenSync$ - Found 1 items on user's watchlist using the plex token
14:44:12.634 [io-compute-10] WARN  PlexTokenSync$ - An error occurred: java.lang.Throwable: DecodingFailure at .data.user.watchlist.pageInfo.endCursor: Got value 'null' with wrong type, expecting string
14:44:13.022 [io-compute-3] WARN  PlexTokenDeleteSync$ - An error occurred: java.lang.Throwable: DecodingFailure at .data.user.watchlist.pageInfo.endCursor: Got value 'null' with wrong type, expecting string`

The main account I'm using with the token is the owner of the server, on the friend account I've tried changing the profile setting for the Watchlist visibility to "Friends" and "Friends of Friends". neither seems to do anything.

This should work without requiring a plex token from the friend, correct?

(Wasn't sure if i should open a new issue, also I'm running the v0.0.11 version released today.)

**Comment by nylonee** [comment]
Oohh this is interesting, thanks for raising this!

It looks like you've got an edge case that I don't have on my watchlist. When the app tries to fetch the results from Plex, there's something missing that causes the sync to fail.

I'll have another proper look at this. Would you be okay to do some debugging for me around this? Unfortunately I got locked out of my house (classic Friday night blunder), but once I'm back in I'll send you some instructions for what information I need.

And to answer your question, yes you're right this is supposed to be able to fetch the watchlist of your friends, without needing their token. Obviously I've only tested this on my own friends, so apologies that it's a little rough getting started, but hopefully we'll get to the bottom of this.

Also the friend just needs to be on "friend" visibility, having them on "friends of friends" is optional

**Comment by Jusremo** [comment]
Sure, I don't mind testing it at all, very excited to get this working, it would honestly be a huge feature addition to Plex.

I just noticed your Reddit message if you prefer to message there, also I'll DM you my discord info on Reddit, thanks for the reply.
