### ISSUE TITLE
Sonarr V3 stopped getting requests from Watchlistarr

### ISSUE THREAD

**Issue by vinc817** [nylonee/watchlistarr#61]
Hi there,
I have Sonarr V3 and I was able to get the requests from my watchlist on Plex. Since yesterday, this seemed to have stopped.
I can see Watchlistarr is sending the shows to Sonarr in the logs but I do not see them in Sonarr.
I reverified my Sonarr API and URL. I restarted both dockers.
I believe Watchlistarr works only on V4 but I wanted to update you here anyway because it used to work.

I wanted to add that, after our chat on reddit (vinc817), I was able to get requests from my friend's watchlists. I created a variable for PLEX_TOKEN in the docker.

**Comment by nylonee** [comment]
Hi! Thanks for raising this, are there any errors in the sonarr logs?

**Comment by vinc817** [comment]
Hey!
No errors. The only thing in the logs was Watchlistarr sending the shows to Sonarr every minute.
Okay, I'll try the new version once I get home.

**Comment by nylonee** [comment]
What I mean is the logs on the sonarr side. They'll probably have some useful information on why the call failed

**Comment by nylonee** [comment]
Resolved offline - the latest version v0.1.1 fixed the issue
