### ISSUE TITLE
Guide to allow syncing with friends 

### ISSUE THREAD

**Issue by abaudhuin** [nylonee/watchlistarr#62]
In the README it's written: 
```
Friends must change their privacy settings so that the main user can see their watchlists
```
How can I do this ?
It should be probably added to the README

**Comment by Jusremo** [comment]
It's in profile settings, privacy. it's part of the new Discover Together system.

**Comment by abaudhuin** [comment]
Thanks !

**Comment by nylonee** [comment]
Thanks for raising this, that's a great point I'll make sure the README has better instructions around this
