### ISSUE TITLE
[Help wanted] First launch errors

### ISSUE THREAD

**Issue by Morzore** [nylonee/watchlistarr#71]
Hello,

First of all I'd like to thank you for creating watchlistarr, it's exactly what I was looking for in order to let my family initiate downloads through Plex.
I'm getting an issue when trying to launch watchlistarr on docker (see logs attached
[Logs watchlistarr.xlsx](https://github.com/nylonee/watchlistarr/files/13840862/Logs.watchlistarr.xlsx)
) and I don't know if it is a misconfiguration on my side or an issue.
I set the following environment variables on top of the default ones on docker :
- PUID
- PGID
- TZ
- SONARR_API_KEY
- RADARR_API_KEY
- PLEX_TOKEN
- REFRESH_INTERVAL_SECONDS (set to 120 not to be too frequent as the log indicates it could be the issue)
- SONARR_BASE_URL
- RADARR_BASE_URL

I'm quite new to docker and radarr/sonarr etc. so I'd like some help understanding if I missed something when setting things up.

Thank you in advance for your help.

Regards,

Morzore

**Comment by nylonee** [comment]
Hello!

Thanks for sending the logs over, I think the issue is that your SONARR_BASE_URL has a slash at the end, so it's trying to reach this URL:
```
http://192.168.1.123/:8989
```
Instead of:
```
http://192.168.1.123:8989
```

I really thought I fixed that issue though (by sanitizing the URL), but I'll re-visit how I did the implementation. Your best fix for now is to make sure that your SONARR_BASE_URL (and also your RADARR_BASE_URL) does not have a slash at the end of the variable

Other key notes:
1. That warning about asynchronous events is a fairly new thing that Scala's introduced. This app is designed to have long-standing asynchronous events, so I will find a way to disable that log. It's not very useful for us in this app
2. I'd say an interval of 5-ish seconds should be fine
3. You don't necessarily need to set the TZ, PUID and PGID (as this app is stateless, and doesn't require file access, it doesn't need a user ID)

**Comment by Morzore** [comment]
Hello!

Thanks a lot, I should have recheck what a dumb mistake.
I modified the configuration according to your advices.

For your information, I was aware it would cause a problem at some point, I didn't take the plex pass subscription yet, if you are interested in the logs it generates when we don't have it I add it here 
[Logs watchlistarr.xlsx](https://github.com/nylonee/watchlistarr/files/13842725/Logs.watchlistarr.xlsx)

For quality profiles it seems to expect a single word, my quality profile was named "HD - 720p/1080p" and it apparently stop at "HD" even though it find the full name, see logs here 
[Logs watchlistarr 2.xlsx](https://github.com/nylonee/watchlistarr/files/13843244/Logs.watchlistarr.2.xlsx)
I workaround creating a dedicated watchlistarr quality profile in one word

Still testing it, for now it doesn't find my friends watchlists but might be because of their configuration, I'll check once with them.

Thank you again for your help.

Regards,

Morzore

**Comment by nylonee** [comment]
Thanks for confirming, the logs when you don't have a plex pass subscription would be quite useful! I'll bookmark that for going through later :)

That's a great catch on the second bug, I imagine I'm doing the name matching wrong. I'll replicate it in my environment and push out a fix shortly.

Could you give more information about how you're doing the friends watchlist? I assume you're using your own plex token, in which case the following criteria need to be met:
1. Your friend needs to show up on this list: https://app.plex.tv/desktop/#!/friends
2. Clicking on their name in that list, you should be able to see a list of their Watchlist items

If both of the above are fine for you, then you've likely hit another bug. If that's the case could you send me the logs that you see when the app first starts up?

**Comment by Morzore** [comment]
Hello again,

Yes on friend's watchlist I figured out they were not friends, I just gave them access to my library, it's fixed now and seem to work like a charm.

I connected with a friend who shared me his library and it came to my mind, if I'm adding friends who have a library and (huge) watchlist I guess the reaction of watchlistarr will be to re-download their watchlist (for example if they trigger download through watchlist too). I tried to find options in Plex to prevent some individuals to see my watchlist / read their watchlist but it seems to be a global parameter. Do you know a workaround in Plex ? If not it could be a feature suggestion to have an environment variable or something like that to prevent parsing their watchlist.

Thanks again for your work, really appreciate it :)

Regards,

Morzore

**Comment by nylonee** [comment]
Unfortunately there isn't an easy way to do this - the RSS feed doesn't tell watchlistarr who's watchlisted something, it only gives a list of things that ALL your friends have watchlisted!

In the future, we could consider a solution that looks up which friend has watchlisted something when a new movie/tv show gets added to the watchlist, but that's fairly costly and will require some careful planning to implement.

**Comment by nylonee** [comment]
Heya, I'm just testing this bug now:
> For quality profiles it seems to expect a single word, my quality profile was named "HD - 720p/1080p" and it apparently stop at "HD" even though it find the full name

I can't seem to replicate it locally with unit tests, can I confirm what your configuration looks like? I wonder if maybe the way you've provided the values has meant that it's not reading the full name, e.g. if you didn't put `""` quotes around the value

**Comment by Morzore** [comment]
Hello,
I tried several cases, first I just copied past the name of the quality profile (without ") next I saw it was mapped to numbers so tried the number, then I tried with "HD - 720p/1080p" and didn't work neither.
