### ISSUE TITLE
Separate root folder for Anime

### ISSUE THREAD

**Issue by nylonee** [nylonee/watchlistarr#80]
A feature request has come in to have separate root folders in Sonarr for anime and non-anime, this may be possible if I can find some indication from the API that a show is anime, but I'll have to check

**Comment by nylonee** [comment]
Yes we can get:
```
        "seriesType": "standard",
```

in the response for each series.

When it's anime, it'll look like:
```
        "seriesType": "anime",
```

Should be straightforward to implement, I'll get cracking soon

**Comment by stamatis921** [comment]
Hi @nylonee, would it be possible to workaround this by allowing using separate root folders/quality profiles for different watchlists? Or even just split off the admin watchlist from friend watchlists? Someone could then use a seperate Plex account for the purpose of maintaining a anime watchlist. Would also be useful for having users on different quality profiles (1080) than the admin (4K).

**Comment by nylonee** [comment]
Hmm interesting idea, it's certainly possible if you have multiple watchlistarr instances running, and you lock down the watchlist syncing to one Plex account by using `SKIP_FRIEND_SYNC=true`. This doesn't require any extra development work on my part.

**Comment by nylonee** [comment]
I definitely would want to support a separate profile/root folder setting natively though, especially for anime.
A possible solution here would be to look up a show, and fetch the metadata which would likely tell me if the show is anime or not.

The work to do this would only affect one function:
https://github.com/nylonee/watchlistarr/blob/main/src/main/scala/sonarr/SonarrUtils.scala#L28-L51

The lookup needs to be fast - using Sonarr's lookup API would be pretty slow and inaccurate. This is the problem at the moment as Sonarr doesn't seem to have a way to lookup metadata without the lookup API (which just takes a string). Trying to get a feature request/PR into Sonarr to improve this is also going to be nearly impossible until [this](https://github.com/Sonarr/Sonarr/issues/6495) is resolved.

So the best alternative is to call the API directly provided by TVDB, which involves setting up yet another API key!
