### ISSUE TITLE
Trakt.tv support?

### ISSUE THREAD

**Issue by Sakooooo** [nylonee/watchlistarr#81]
Are there any plans for trakt.tv support? This looks nice but I don't use plex so I was wondering if there would be trakt.tv support sometime.

**Comment by nylonee** [comment]
There very well could be, if there's enough interest. I'll take a look at the API docs and see if I can decipher what I need to get this integration working

**Comment by Sakooooo** [comment]
> There very well could be, if there's enough interest. I'll take a look at the API docs and see if I can decipher what I need to get this integration working

Thanks!

**Comment by nylonee** [comment]
So I've had more of a think about this, and I'm not quite sure what's the best way to implement this.

I think what you're looking for is already natively implemented into Sonarr/Radarr (see picture)
![Screenshot 2024-02-16 164338](https://github.com/nylonee/watchlistarr/assets/4732553/d8bca1fd-f3b3-4701-bd57-67e3cdd5ed49)

Could you give some more details of what exactly you're looking for? Understanding your use case better would help me understand if this is something that can be integrated as part of Watchlistarr

**Comment by Sakooooo** [comment]
> So I've had more of a think about this, and I'm not quite sure what's the best way to implement this.
> 
> I think what you're looking for is already natively implemented into Sonarr/Radarr (see picture) ![Screenshot 2024-02-16 164338](https://private-user-images.githubusercontent.com/4732553/305482980-d8bca1fd-f3b3-4701-bd57-67e3cdd5ed49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMDM0NTksIm5iZiI6MTcwODEwMzE1OSwicGF0aCI6Ii80NzMyNTUzLzMwNTQ4Mjk4MC1kOGJjYTFmZC1mM2IzLTQ3MDEtYmQ1Ny02N2UzY2RkNWVkNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTcwNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGMwNjNhNmZmMGZiYWQ5NzZlM2ViNmNmMjMzMDEyZjgxNzYwMGQwYjQxYzc1ZjhhYTVmZTQ4MDJiMTA2MGM1OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.I75a3Paw23PP7QNpeVGzll3iNiu6hMoh5XBwG6oBicU)
> 
> Could you give some more details of what exactly you're looking for? Understanding your use case better would help me understand if this is something that can be integrated as part of Watchlistarr

watchlistarr has a Plex watchlist real time sync and I was wondering if the same could work with trakt cause this needs plex pass

**Comment by nylonee** [comment]
So doing a sync between Plex and Trakt?

How does that help you in your use case? You said earlier that:
> I don't use plex

If you're indeed looking for something that can sync Plex to Trakt (without requiring Trakt VIP and Plex Pass), have you considered [PlexTraktSync](https://github.com/Taxel/PlexTraktSync)?

**Comment by Sakooooo** [comment]
I meant to sonarr/radarr, but this looks good too Ill check it out!

**Comment by nylonee** [comment]
So Watchlistarr is pretty tightly coupled with Plex unfortunately, if you're looking for something that doesn't touch Plex at all and does a request sync, I think there are other better options (e.g. built into Sonarr/Radarr)

If you're looking for something that syncs Plex to Trakt.tv, then PlexTraktSync will do a far better job than I ever will

I think I'll close this now as I don't quite see a future where Watchlistarr can work to do a sync with Trakt.tv. Sorry

**Comment by Sakooooo** [comment]
> So Watchlistarr is pretty tightly coupled with Plex unfortunately, if you're looking for something that doesn't touch Plex at all and does a request sync, I think there are other better options (e.g. built into Sonarr/Radarr)
> 
> 
> 
> If you're looking for something that syncs Plex to Trakt.tv, then PlexTraktSync will do a far better job than I ever will
> 
> 
> 
> I think I'll close this now as I don't quite see a future where Watchlistarr can work to do a sync with Trakt.tv. Sorry

alright, thanks though!
